version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${REACT_APP_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${REACT_APP_MONGO_PASS}
    networks:
      employee-dev:
        ipv4_address: 97.1.1.1
networks:
  employee-dev:
    ipam:
      driver: default
      config:
        - subnet: 97.1.1.0/16