version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#TO RUN DATABASE LOCALLY FROM THE CLI
#RUN yarn start-db FROM AN EXTERNAL
#TERMINAL (NOT INSIDE THE DEV CONTAINER)

#IMPORTANT!!!  FOR ACCESS TO MONGO GUI, HIT:
#HTTP://LOCALHOST:8081 AFTER STARTING MONGO.