version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      employee-dev:
        ipv4_address: ${MONGO_IP}
networks:
  employee-dev:
    ipam:
      driver: default
      config:
        - subnet: 97.1.1.0/16