export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS";
export const GET_EMPLOYEE_ORG = "GET_EMPLOYEE_ORG";
export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING';
export const SWITCH_DISPLAY = "SWITCH_DISPLAY";

export const AZURE_USERLOADING = "AZURE_USERLOADING";
export const AZURE_USERLOADED = "AZURE_USERLOADED";
export const AZURE_AUTHERROR = "AZURE_AUTHERROR";
export const AZURE_LOGIN_OK = "AZURE_LOGIN_OK";
export const AZURE_LOGIN_FAIL = "AZURE_LOGIN_FAIL";
export const AZURE_LOGOUT = "AZURE_LOGOUT";
export const AZURE_REGISTER_OK = "AZURE_REGISTER_OK";
export const AZURE_REGISTER_FAIL = "AZURE_REGISTER_FAIL";

