export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS";
export const GET_EMPLOYEE_ORG = "GET_EMPLOYEE_ORG";
export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING';
