name: dts-test-publish-deploy

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
#   testing:
#     name: testing
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: run docker compose
#       run: docker-compose up --exit-code-from e2e
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test true
      run: return 1


  publish_Deploy:
    name: Publish and Deploy
    #needs: testing
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    # - name: Print new build number
    #   run: echo Build number is $BUILD_NUMBER   
    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: mtscontainers.azurecr.io
    #     username: ${{ secrets.DTS_AZURE_USERNAME }}
    #     password: ${{ secrets.DTS_AZURE_PASSWORD }}
    # - uses: actions/checkout@v1
    # - name: docker build and push
    #   run: |
    #     docker build --build-arg DB_NAME=temp -t mtscontainers.azurecr.io/dts-scheduler:latest .
    #     docker tag mtscontainers.azurecr.io/dts-scheduler:latest mtscontainers.azurecr.io/dts-scheduler:$BUILD_NUMBER
    #     docker push mtscontainers.azurecr.io/dts-scheduler:latest
    #     docker push mtscontainers.azurecr.io/dts-scheduler:$BUILD_NUMBER
    # - name: curl
    #   uses: wei/curl@v1
    #   with:
    #     args: -X POST https://jenkins.esdc.online/job/dts-scheduler/buildWithParameters?docker_tag=$BUILD_NUMBER --user jenkinsbot:${{ secrets.DTS_JENKINS_TOKEN }}
